name: 'cd'
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  CI: true
jobs:
  test:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: shell lint
        uses: actions/bin/shellcheck@master
        with:
          args: 'entrypoint.sh'
      - name: bats test
        uses: actions/bin/bats@master
        with:
          args: 'test/*.bats'
      - name: docker lint
        uses: docker://replicated/dockerfilelint
        with:
          args: 'Dockerfile'
      - name: docker build
        uses: actions/docker/cli@master
        with:
          args: 'build -t actions-yarn .'
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: shell lint
        uses: actions/bin/shellcheck@master
        with:
          args: 'entrypoint.sh'
      - name: bats test
        uses: actions/bin/bats@master
        with:
          args: 'test/*.bats'
      - name: docker lint
        uses: docker://replicated/dockerfilelint
        with:
          args: 'Dockerfile'
      - name: docker build
        uses: actions/docker/cli@master
        with:
          args: 'build -t actions-yarn .'
      - name: docker tag
        uses: actions/docker/tag@master
        with:
          args: 'actions-yarn justinharringa/actions-yarn --no-latest'
      - name: docker login
        uses: actions/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: docker push
        uses: actions/docker/cli@master
        with:
          args: 'push justinharringa/actions-yarn'
